AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'AWS Cloud Formation Template for RDS DB Creation'
Parameters:
  DBName:
    Default: MySQLDB
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBUser:
    NoEcho: 'true'
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  DBClass:
    Default: db.t2.small
    Description: Select the DB Classs
    Type: String
    AllowedValues:
    - db.t2.small
    - db.t2.micro
    - db.t2.medium
  Storage:
    Description: Enter the Capacity of DBInstanceClass
    Type: String
    AllowedPattern: '[0-9]*'
  EngineVersion:
    Default: 5.6.37
    Description: Select the MySQL Engine Version
    Type: String
    AllowedValues:
      - 5.7.19
      - 5.7.17
      - 5.7.16
      - 5.6.37
      - 5.6.35
      - 5.6.34
      - 5.6.29
      - 5.6.27
      - 5.5.57
      - 5.5.54
      - 5.5.53
      - 5.5.46
Resources:
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref 'DBName'
      AllocatedStorage: !Ref 'Storage'
      DBInstanceClass: !Ref 'DBClass'
      Engine: MySQL
      EngineVersion: !Ref 'EngineVersion'
      MasterUsername: !Ref 'DBUser'
      MasterUserPassword: !Ref 'DBPassword'
      DBParameterGroupName: !Ref 'MyRDSParamGroup'
      BackupRetentionPeriod: 0
      DBInstanceIdentifier: wls
  MyRDSParamGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Family: MySQL5.6
      Description: CloudFormation Sample Database Parameter Group
      Parameters:
        autocommit: '1'
        general_log: '1'
        old_passwords: '0'
Outputs:
  JDBCConnectionString:
    Description: JDBC connection string for the database
    Value: !Join ['', ['jdbc:mysql://', !GetAtt [MyDB, Endpoint.Address], ':', !GetAtt [
          MyDB, Endpoint.Port], /, !Ref 'DBName']]
  RDSHostname:
    Description: RDS Hostname
    Value:
      Fn::GetAtt:
      - MyDB
      - Endpoint.Address
  RDSPort:
    Description: RDS Port
    Value:
      Fn::GetAtt:
      - MyDB
      - Endpoint.Port
